### ISSUE TITLE
Check Result

### ISSUE THREAD

**Issue by yegor92** [yegor92/Inaccord#1]
Hi, How are you?
I have finished your test task.
Implemented it using TypeScript, React Hook and Styled Component.
In addition, used React-Storybook.
Please check and give me your opinion.
Regards.
Yegor.
(I sent proposal on upwork. My full name is Yegor Yanushkevich)

**Comment by yegor92** [comment]
Could you please clone repository and run locally?

**Comment by kilianc** [comment]
I did, and I got that error @yegor92

**Comment by kilianc** [comment]
![image](https://user-images.githubusercontent.com/385716/73412074-54ab0380-42bc-11ea-84d3-f17b343810c1.png)

**Comment by yegor92** [comment]
Do you get this when `yarn dev`?

**Comment by yegor92** [comment]
Could you please pull and try again?

**Comment by yegor92** [comment]
Do you still have same issue?

**Comment by yegor92** [comment]
![Screen Shot 2020-01-30 at 2 53 42 AM](https://user-images.githubusercontent.com/30550824/73413369-c199ba00-430b-11ea-8242-039418e1a75e.png)
In my side, it's working well.

**Comment by kilianc** [comment]
![image](https://user-images.githubusercontent.com/385716/73413371-524aa880-42c0-11ea-8933-bca1ccabeb7a.png)

**Comment by kilianc** [comment]
Your OS is case insensitive, really bad practice.

![image](https://user-images.githubusercontent.com/385716/73413548-dd2ba300-42c0-11ea-8b05-71872afa6667.png)

**Comment by yegor92** [comment]
So It's working?

**Comment by yegor92** [comment]
Or should I upload result to the codesandbox?
